### ISSUE TITLE
I'm having the same problem when posting messages using Slacks api, it sometimes also return a 100 Continue before the 200 OK.

### ISSUE THREAD

**Issue by vero555** [tcdent/php-restclient#39] opened 2020-10-13 15:52 UTC
I'm having the same problem when posting messages using Slacks api, it sometimes also return a 100 Continue before the 200 OK.

_Publicación original de @pakomp en https://github.com/tcdent/php-restclient/issues/38#issuecomment-696062149_

**Comment by tcdent** [comment] 2022-04-08 15:58
Duplicate of #38

**Closed by tcdent** 2022-04-08 15:58 UTC
